// Generated by Switchboard's Code Rewriter — the drop-in replacement for
// supabaseClient.ts. Same idea (one client every module imports), but it talks
// to the generated Aiven API instead of Supabase. This is the ONLY new concept
// the rest of the app sees; auth.ts / db.ts / realtime.ts keep their signatures.
// Single-service deploy: the API serves this built SPA, so default to same-origin
// (relative paths) in production. Dev still talks to the local API on :8089.
const BASE = (import.meta.env.VITE_API_URL as string) ?? (import.meta.env.PROD ? '' : 'http://localhost:8089')
const TOKEN_KEY = 'pb_token'

export function getToken(): string | null {
  return localStorage.getItem(TOKEN_KEY)
}
export function setToken(token: string | null) {
  if (token) localStorage.setItem(TOKEN_KEY, token)
  else localStorage.removeItem(TOKEN_KEY)
}

export async function apiFetch(path: string, init: RequestInit = {}): Promise<any> {
  const token = getToken()
  const res = await fetch(BASE + path, {
    ...init,
    headers: {
      'content-type': 'application/json',
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...(init.headers || {}),
    },
  })
  if (!res.ok) {
    const msg = await res.json().catch(() => ({}))
    throw new Error(msg.error || res.statusText)
  }
  return res.status === 204 ? null : res.json()
}

export { BASE }
