// surgeon/templates.ts — the parameterized backend file templates.
//
// Each function returns the full source text for one generated file, modeled 1:1 on
// demo/pulsewall-aiven/server/*.ts. They take the derived TableModel[] so the data API,
// schema, and vector search are specific to the source app's tables — not hard-coded to
// PulseWall. The realtime bridge, JWT auth, and bytea storage are app-independent and
// rendered verbatim from the reference shape.
//
// Everything here is pure string-building: no IO, no env reads, no throws.

import type { TableModel, ColumnModel } from './model.ts'
import { typeName } from './model.ts'

const HEADER = '// GENERATED by Overmind Surgeon — Aiven-native backend. Do not edit by hand;\n// re-run the migration to regenerate. Modeled on demo/pulsewall-aiven.\n'

const pkOf = (t: TableModel): ColumnModel => t.columns.find((c) => c.isPrimaryKey) ?? t.columns[0]
const cols = (t: TableModel): string => t.columns.map((c) => c.name).join(', ')
const writableCols = (t: TableModel): ColumnModel[] =>
  t.columns.filter((c) => !c.isPrimaryKey && c.name !== 'created_at' && !(t.vectorColumn && c.name === t.vectorColumn))

// ───────────────────────────── env.ts ─────────────────────────────
export function envTs(): string {
  return `${HEADER}// Load env before anything else reads process.env. Import FIRST in every entrypoint.
import { config } from 'dotenv'
import { existsSync } from 'node:fs'

if (existsSync('.env.local')) config({ path: '.env.local' })
config()
`
}

// ───────────────────────────── db.ts ─────────────────────────────
export function dbTs(): string {
  return `${HEADER}import { Pool } from 'pg'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const url = process.env.DATABASE_URL ?? ''

function makePool(): Pool {
  if (!url) return new Pool() // unconfigured — errors clearly until DATABASE_URL is set
  const u = new URL(url)
  u.searchParams.delete('sslmode')
  let ssl: any
  if (process.env.PROJECT_CA_CERT) {
    ssl = { ca: Buffer.from(process.env.PROJECT_CA_CERT, 'base64').toString('utf8'), rejectUnauthorized: true }
  } else if (url.includes('aivencloud.com') || url.includes('sslmode=require')) {
    ssl = { rejectUnauthorized: false }
  }
  return new Pool({ connectionString: u.toString(), ssl, max: 10 })
}

export const pool = makePool()

export async function q<T = any>(text: string, params: any[] = []): Promise<T[]> {
  const res = await pool.query(text, params)
  return res.rows as T[]
}
export async function q1<T = any>(text: string, params: any[] = []): Promise<T | null> {
  const rows = await q<T>(text, params)
  return rows[0] ?? null
}

/** Apply db/schema.sql (idempotent). */
export async function applySchema(): Promise<void> {
  const sql = readFileSync(join(__dirname, '..', 'db', 'schema.sql'), 'utf8')
  await pool.query(sql)
}

export function dbConfigured(): boolean {
  return !!url
}
`
}

// ───────────────────────────── auth.ts (own JWT-shaped auth) ─────────────────────────────
export function authTs(): string {
  return `${HEADER}import { createHmac, randomInt, timingSafeEqual } from 'node:crypto'
import { q, q1 } from './db.ts'

export interface User { id: string; email: string; handle: string; created_at: string }

const SECRET = process.env.AUTH_SECRET || 'dev-secret-change-me'
const WEEK = 1000 * 60 * 60 * 24 * 7

function b64url(buf: Buffer | string): string { return Buffer.from(buf).toString('base64url') }

/** HMAC-signed token (JWT-shaped) — replaces Supabase GoTrue sessions. */
export function signToken(sub: string, email: string): string {
  const body = b64url(JSON.stringify({ sub, email, exp: Date.now() + WEEK }))
  const sig = b64url(createHmac('sha256', SECRET).update(body).digest())
  return \`\${body}.\${sig}\`
}

export function verifyToken(token: string | undefined): { sub: string; email: string } | null {
  if (!token) return null
  const [body, sig] = token.split('.')
  if (!body || !sig) return null
  const expected = b64url(createHmac('sha256', SECRET).update(body).digest())
  const a = Buffer.from(sig), b = Buffer.from(expected)
  if (a.length !== b.length || !timingSafeEqual(a, b)) return null
  try {
    const data = JSON.parse(Buffer.from(body, 'base64url').toString())
    if (data.exp && data.exp < Date.now()) return null
    return { sub: data.sub, email: data.email }
  } catch { return null }
}

export function handleFromEmail(email: string): string {
  return email.split('@')[0].replace(/[^a-zA-Z0-9_]/g, '').slice(0, 20) || 'user'
}

/** Issue a magic code (replaces Supabase magic-link email). Returned in dev; emailed in prod. */
export async function requestCode(email: string): Promise<string> {
  const code = String(randomInt(100000, 999999))
  await q(\`insert into auth_codes (email, code, expires_at) values ($1, $2, now() + interval '10 minutes')\`, [email, code])
  return code
}

export async function verifyCode(email: string, code: string): Promise<User | null> {
  const row = await q1<{ code: string }>(
    \`select code from auth_codes where email = $1 and expires_at > now() order by created_at desc limit 1\`,
    [email],
  )
  if (!row || row.code !== code) return null
  await q(\`delete from auth_codes where email = $1\`, [email])
  return await q1<User>(
    \`insert into users (email, handle) values ($1, $2)
     on conflict (email) do update set handle = users.handle
     returning id, email, handle, created_at\`,
    [email, handleFromEmail(email)],
  )
}

export async function getUserFromToken(token: string | undefined): Promise<User | null> {
  const claims = verifyToken(token)
  if (!claims) return null
  return await q1<User>(\`select id, email, handle, created_at from users where id = $1\`, [claims.sub])
}

export function bearer(header: string | undefined | null): string | undefined {
  if (!header) return undefined
  const m = header.match(/^Bearer\\s+(.+)$/i)
  return m ? m[1] : undefined
}
`
}

// ───────────────────────────── bus.ts (Kafka → SSE realtime bridge) ─────────────────────────────
export function busTs(): string {
  return `${HEADER}import { EventEmitter } from 'node:events'
import { readFileSync } from 'node:fs'

// Realtime spine. publish() → Aiven Kafka (cross-instance) → consumer → onEvent() → SSE.
// No Kafka configured? falls back to an in-process EventEmitter so dev still works.

export type BusEvent = { type: string; table?: string; row?: any; [k: string]: any }

const emitter = new EventEmitter()
emitter.setMaxListeners(0)

const TOPIC = process.env.KAFKA_TOPIC || 'overmind.app.outbox'
const BROKERS = process.env.KAFKA_BROKERS || process.env.KAFKA_BOOTSTRAP_SERVER || ''
const useKafka = !!BROKERS

let producer: any = null
let kafkaReady = false

async function initKafka(): Promise<void> {
  if (!useKafka) { console.log('[bus] in-process mode (set KAFKA_BROKERS to use Aiven Kafka)'); return }
  const { Kafka, logLevel } = await import('kafkajs')
  const ssl = process.env.KAFKA_SSL_CA_PATH
    ? { ca: [readFileSync(process.env.KAFKA_SSL_CA_PATH, 'utf8')], rejectUnauthorized: true }
    : true
  const kafka = new Kafka({
    clientId: 'overmind-app',
    brokers: process.env.KAFKA_BROKERS!.split(',').map((b) => b.trim()),
    ssl,
    sasl: process.env.KAFKA_PASSWORD
      ? { mechanism: 'scram-sha-256', username: process.env.KAFKA_USERNAME!, password: process.env.KAFKA_PASSWORD! }
      : undefined,
    logLevel: logLevel.ERROR,
  })
  producer = kafka.producer()
  await producer.connect()
  const groupId = \`overmind-sse-\${process.pid}-\${Date.now()}\` // unique → fan-out, not work-split
  const consumer = kafka.consumer({ groupId })
  await consumer.connect()
  await consumer.subscribe({ topic: TOPIC, fromBeginning: false })
  await consumer.run({
    eachMessage: async ({ message }) => {
      if (!message.value) return
      try { emitter.emit('event', JSON.parse(message.value.toString())) } catch { /* ignore */ }
    },
  })
  kafkaReady = true
  console.log(\`[bus] Aiven Kafka connected → topic "\${TOPIC}"\`)
}

export const busReady: Promise<void> = initKafka().catch((e) => {
  console.error('[bus] Kafka init failed — falling back to in-process bus:', e?.message ?? e)
})

export async function publish(event: BusEvent): Promise<void> {
  if (useKafka && producer && kafkaReady) {
    const key = event?.row?.id ?? event?.table ?? ''
    await producer.send({ topic: TOPIC, messages: [{ key: String(key), value: JSON.stringify(event) }] })
  } else {
    emitter.emit('event', event)
  }
}

export function onEvent(fn: (e: BusEvent) => void): () => void {
  emitter.on('event', fn)
  return () => emitter.off('event', fn)
}

export function busMode(): string {
  if (!useKafka) return 'in-process'
  return kafkaReady ? 'aiven-kafka' : 'aiven-kafka(connecting)'
}
`
}

// ───────────────────────────── embeddings.ts (pgvector source) ─────────────────────────────
export function embeddingsTs(dim: number): string {
  return `${HEADER}// Vector embeddings — direct embedding API call (no Supabase edge fn / Lovable gateway).
// text-embedding-3-small → vector(${dim}). Swap model/provider freely.

const KEY = process.env.OPENAI_API_KEY

export function embeddingsEnabled(): boolean { return !!KEY }

export async function embed(text: string): Promise<number[] | null> {
  if (!KEY) return null
  try {
    const res = await fetch('https://api.openai.com/v1/embeddings', {
      method: 'POST',
      headers: { Authorization: \`Bearer \${KEY}\`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: 'text-embedding-3-small', input: text }),
    })
    if (!res.ok) { console.error('[embed] failed', res.status, await res.text()); return null }
    const data = (await res.json()) as { data: { embedding: number[] }[] }
    return data.data[0].embedding as number[]
  } catch (e) { console.error('[embed] error', e); return null }
}

/** pgvector accepts a literal like "[0.1,0.2,...]". */
export function toVectorLiteral(v: number[]): string { return \`[\${v.join(',')}]\` }
`
}

// ───────────────────────────── storage.ts (bytea storage) ─────────────────────────────
export function storageTs(): string {
  return `${HEADER}import { q, q1 } from './db.ts'

// Image/blob storage — bytes live in Aiven Postgres (bytea). Replaces Supabase Storage.
// Keeps the whole app on Aiven. (At real scale, front this with S3-compatible storage.)

export async function putImage(bytes: Buffer, mime: string, ownerId: string | null): Promise<string> {
  const row = await q1<{ id: string }>(
    \`insert into images (mime, bytes, owner_id) values ($1, $2, $3) returning id\`,
    [mime, bytes, ownerId],
  )
  return row!.id
}

export async function getImage(id: string): Promise<{ mime: string; bytes: Buffer } | null> {
  return await q1<{ mime: string; bytes: Buffer }>(\`select mime, bytes from images where id = $1\`, [id])
}
`
}

// ───────────────────────────── routes.ts (data API over Aiven PG) ─────────────────────────────
function tableRoutes(t: TableModel): string {
  const T = typeName(t.name)
  const pk = pkOf(t)
  const colList = cols(t)
  const wcols = writableCols(t)
  const insertCols = wcols.map((c) => c.name)
  const placeholders = insertCols.map((_, i) => `$${i + 1}`).join(', ')
  const owner = t.ownerColumn
  // body-extraction (only writable, non-owner columns come from the request body)
  const bodyCols = insertCols.filter((c) => c !== owner)

  const insertValues = insertCols
    .map((c) => (c === owner ? 'user.id' : `body.${c} ?? null`))
    .join(', ')

  const searchRoute = t.vectorColumn
    ? `
  // semantic search over ${t.name}.${t.vectorColumn} (Aiven pgvector)
  api.post('/${t.name}/search', async (c) => {
    const { query } = await c.req.json().catch(() => ({}))
    const text = String(query ?? '').trim()
    if (!text) return c.json({ results: [] })
    if (!embeddingsEnabled()) return c.json({ error: 'search disabled (set OPENAI_API_KEY)', results: [] })
    const v = await embed(text)
    if (!v) return c.json({ error: 'embedding failed', results: [] })
    const results = await q('select * from match_${t.name}($1, 12)', [toVectorLiteral(v)])
    return c.json({ results })
  })`
    : ''

  const embedAfterInsert =
    t.vectorColumn && bodyCols.some((c) => c === 'body' || c === 'text' || c === 'content')
      ? `
    // background embed → pgvector search (fire-and-forget)
    void (async () => {
      const src = String(${bodyCols.includes('body') ? 'body.body' : bodyCols.includes('text') ? 'body.text' : 'body.content'} ?? '')
      if (!src) return
      const v = await embed(src)
      if (v) await q('update ${t.name} set ${t.vectorColumn} = $1 where ${pk.name} = $2', [toVectorLiteral(v), row.${pk.name}])
    })()`
      : ''

  return `
  // ── ${t.name} ──────────────────────────────────────────────────
  api.get('/${t.name}', async (c) => {
    const rows = await q<${T}>(\`select ${colList} from ${t.name} order by ${t.orderColumn} desc limit 100\`)
    return c.json({ ${t.name}: rows })
  })

  api.get('/${t.name}/:id', async (c) => {
    const row = await q1<${T}>(\`select ${colList} from ${t.name} where ${pk.name} = $1\`, [c.req.param('id')])
    if (!row) return c.json({ error: 'not found' }, 404)
    return c.json({ ${typeName(t.name).toLowerCase()}: row })
  })

  api.post('/${t.name}', async (c) => {
    const user = await authUser(c)
    if (!user) return c.json({ error: 'sign in required' }, 401)
    const body = await c.req.json().catch(() => ({}))
    const row = await q1<${T}>(
      \`insert into ${t.name} (${insertCols.join(', ')}) values (${placeholders}) returning ${colList}\`,
      [${insertValues}],
    )
    if (!row) return c.json({ error: 'insert failed' }, 500)
    await publish({ type: '${t.name}.created', table: '${t.name}', row })${embedAfterInsert}
    return c.json({ ${typeName(t.name).toLowerCase()}: row })
  })

  api.delete('/${t.name}/:id', async (c) => {
    const user = await authUser(c)
    if (!user) return c.json({ error: 'sign in required' }, 401)
    ${
      owner
        ? `const owned = await q1(\`select 1 from ${t.name} where ${pk.name} = $1 and ${owner} = $2\`, [c.req.param('id'), user.id])
    if (!owned) return c.json({ error: 'not yours' }, 403)`
        : ''
    }
    await q(\`delete from ${t.name} where ${pk.name} = $1\`, [c.req.param('id')])
    await publish({ type: '${t.name}.deleted', table: '${t.name}', row: { ${pk.name}: c.req.param('id') } })
    return c.json({ ok: true })
  })
${searchRoute}`
}

export function routesTs(models: TableModel[]): string {
  const anyVector = models.some((m) => m.vectorColumn)
  const statsTables = models.map((m) => `      ${m.name}: Number((await q<{ n: string }>('select count(*)::text n from ${m.name}'))[0]?.n ?? 0),`).join('\n')
  const typeDecls = models
    .map((t) => `interface ${typeName(t.name)} { ${t.columns.map((c) => `${c.name}: any`).join('; ')} }`)
    .join('\n')

  return `${HEADER}import { Hono } from 'hono'
import { streamSSE } from 'hono/streaming'
import { q, q1 } from './db.ts'
import { bearer, getUserFromToken, requestCode, verifyCode, signToken, type User } from './auth.ts'
import { publish, onEvent, busMode } from './bus.ts'${
    anyVector ? "\nimport { embed, embeddingsEnabled, toVectorLiteral } from './embeddings.ts'" : ''
  }
import { putImage, getImage } from './storage.ts'

${typeDecls}

export const api = new Hono()

async function authUser(c: any): Promise<User | null> {
  return getUserFromToken(bearer(c.req.header('Authorization')))
}

// ── Health / stats ──────────────────────────────────────────────
api.get('/health', (c) => c.json({ ok: true, bus: busMode()${anyVector ? ', embeddings: embeddingsEnabled()' : ''} }))

api.get('/stats', async (c) => {
  return c.json({
${statsTables}
    bus: busMode(),${anyVector ? '\n    embeddings: embeddingsEnabled(),' : ''}
  })
})

// ── Auth (our own — replaces Supabase GoTrue) ───────────────────
api.post('/auth/request', async (c) => {
  const { email } = await c.req.json().catch(() => ({}))
  if (!email || typeof email !== 'string') return c.json({ error: 'email required' }, 400)
  const code = await requestCode(email.toLowerCase().trim())
  console.log(\`[auth] magic code for \${email}: \${code}\`)
  const dev = process.env.AUTH_DEV === 'true'
  return c.json({ ok: true, ...(dev ? { code } : {}) })
})

api.post('/auth/verify', async (c) => {
  const { email, code } = await c.req.json().catch(() => ({}))
  const user = await verifyCode(String(email).toLowerCase().trim(), String(code).trim())
  if (!user) return c.json({ error: 'invalid or expired code' }, 401)
  return c.json({ token: signToken(user.id, user.email), user })
})

api.get('/me', async (c) => c.json({ user: await authUser(c) }))

// ── Data API (generated per source table) ───────────────────────${models.map(tableRoutes).join('\n')}

// ── Realtime: Kafka → SSE ───────────────────────────────────────
api.get('/stream', (c) =>
  streamSSE(c, async (stream) => {
    await stream.writeSSE({ event: 'hello', data: JSON.stringify({ bus: busMode() }) })
    const off = onEvent((e) => { stream.writeSSE({ event: 'pulse', data: JSON.stringify(e) }).catch(() => {}) })
    const heartbeat = setInterval(() => { stream.writeSSE({ event: 'ping', data: '1' }).catch(() => {}) }, 25000)
    stream.onAbort(() => { off(); clearInterval(heartbeat) })
    while (!stream.aborted) { await stream.sleep(60000) }
  }),
)

// ── Images (Aiven PG bytea — replaces Supabase Storage) ─────────
api.post('/images', async (c) => {
  const user = await authUser(c)
  if (!user) return c.json({ error: 'sign in to upload' }, 401)
  const body = await c.req.parseBody()
  const file = body['file']
  if (!(file instanceof File)) return c.json({ error: 'file required' }, 400)
  const buf = Buffer.from(await file.arrayBuffer())
  if (buf.length > 5 * 1024 * 1024) return c.json({ error: 'image too large (max 5MB)' }, 400)
  const id = await putImage(buf, file.type || 'image/jpeg', user.id)
  return c.json({ id, url: \`/api/images/\${id}\` })
})

api.get('/images/:id', async (c) => {
  const img = await getImage(c.req.param('id'))
  if (!img) return c.notFound()
  return new Response(img.bytes, {
    headers: { 'Content-Type': img.mime, 'Cache-Control': 'public, max-age=31536000, immutable' },
  })
})
`
}

// ───────────────────────────── index.ts (entrypoint) ─────────────────────────────
export function indexTs(): string {
  return `${HEADER}import './env.ts'
import { readFileSync } from 'node:fs'
import { serve } from '@hono/node-server'
import { serveStatic } from '@hono/node-server/serve-static'
import { Hono } from 'hono'
import { api } from './routes.ts'
import { busReady, busMode } from './bus.ts'
import { applySchema, dbConfigured } from './db.ts'

const app = new Hono()
app.route('/api', api)

const isProd = process.env.NODE_ENV === 'production'
if (isProd) {
  app.use('/*', serveStatic({ root: './dist' }))
  app.notFound((c) => {
    try { return c.html(readFileSync('./dist/index.html', 'utf8')) }
    catch { return c.text('client not built — run \`npm run build\`', 500) }
  })
}

const port = Number(process.env.PORT || 8789)

async function boot() {
  if (dbConfigured()) {
    try { await applySchema(); console.log('[db] schema applied to Aiven Postgres') }
    catch (e) { console.error('[db] schema apply failed:', (e as Error).message) }
  } else {
    console.warn('[db] DATABASE_URL not set — API will error until you point it at Aiven')
  }
  await busReady
  serve({ fetch: app.fetch, port, hostname: '0.0.0.0' }, (info) => {
    console.log(\`⚡ Overmind-generated backend (Aiven-native) on http://0.0.0.0:\${info.port}  ·  bus=\${busMode()}\`)
  })
}

boot()
`
}

// ───────────────────────────── apply-schema.ts ─────────────────────────────
export function applySchemaTs(): string {
  return `${HEADER}import './env.ts'
import { applySchema, dbConfigured, pool } from './db.ts'

if (!dbConfigured()) {
  console.error('DATABASE_URL not set. Point it at your Aiven Postgres (.env.local).')
  process.exit(1)
}
await applySchema()
console.log('✅ schema applied to Aiven Postgres')
await pool.end()
`
}

// ───────────────────────────── schema.sql ─────────────────────────────
function colDdl(c: ColumnModel): string {
  const parts = [`  ${c.name}`, c.type]
  if (c.isPrimaryKey) parts.push('primary key')
  if (!c.nullable && !c.isPrimaryKey) parts.push('not null')
  if (c.default) parts.push(`default ${c.default}`)
  if (c.references) parts.push(`references ${c.references} on delete cascade`)
  return parts.join(' ')
}

function tableDdl(t: TableModel): string {
  const lines = t.columns.map(colDdl).join(',\n')
  let out = `create table if not exists ${t.name} (\n${lines}\n);\n`
  out += `create index if not exists ${t.name}_${t.orderColumn}_idx on ${t.name} (${t.orderColumn} desc);\n`
  if (t.vectorColumn) {
    const dim = t.vectorDim ?? 1536
    // the search result columns are every column EXCEPT the vector itself (+ a similarity score)
    const resultCols = t.columns.filter((c) => c.name !== t.vectorColumn)
    out += `create index if not exists ${t.name}_${t.vectorColumn}_idx on ${t.name} using hnsw (${t.vectorColumn} vector_cosine_ops);\n`
    out += `\n-- semantic search RPC for ${t.name}\n`
    out += `create or replace function match_${t.name}(query_embedding vector(${dim}), match_count int default 12)\n`
    out += `returns table (${resultCols.map((c) => `${c.name} ${c.type}`).join(', ')}, similarity float)\n`
    out += `language sql stable as $$\n`
    out += `  select ${resultCols.map((c) => `x.${c.name}`).join(', ')}, 1 - (x.${t.vectorColumn} <=> query_embedding) as similarity\n`
    out += `  from ${t.name} x where x.${t.vectorColumn} is not null\n`
    out += `  order by x.${t.vectorColumn} <=> query_embedding limit match_count;\n$$;\n`
  }
  return out
}

export function schemaSql(models: TableModel[]): string {
  const needsVector = models.some((m) => m.vectorColumn)
  let sql = `-- GENERATED by Overmind Surgeon — Aiven-native schema. Zero Supabase.
-- We own auth (no auth.users), images live in PG bytea (no storage.objects),
-- realtime is Aiven Kafka (no supabase_realtime publication), no pg_net / edge fns.

`
  if (needsVector) sql += `create extension if not exists vector;\n`
  sql += `create extension if not exists pgcrypto;   -- gen_random_uuid()\n\n`

  sql += `-- ── Identity (our own auth — replaces Supabase GoTrue) ──────────────────────────
create table if not exists users (
  id          uuid primary key default gen_random_uuid(),
  email       text not null unique,
  handle      text not null,
  created_at  timestamptz not null default now()
);

create table if not exists auth_codes (
  email       text not null,
  code        text not null,
  expires_at  timestamptz not null,
  created_at  timestamptz not null default now()
);
create index if not exists auth_codes_email_idx on auth_codes (email);

-- ── Storage (replaces Supabase Storage — bytes live in Aiven PG) ────────────────
create table if not exists images (
  id          uuid primary key default gen_random_uuid(),
  mime        text not null,
  bytes       bytea not null,
  owner_id    uuid references users(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- ── Source tables (migrated to Aiven Postgres) ──────────────────────────────────
`

  // emit source tables in dependency order (tables with no FK refs first)
  const ordered = [...models].sort((a, b) => {
    const aRefs = a.columns.some((c) => c.references && !c.references.startsWith('users'))
    const bRefs = b.columns.some((c) => c.references && !c.references.startsWith('users'))
    return aRefs === bRefs ? 0 : aRefs ? 1 : -1
  })
  sql += ordered.map(tableDdl).join('\n')

  sql += `\n-- ── Operational tables (migrator receipts + CTO agent) ──────────────────────────
create table if not exists migration_receipts (
  id      bigserial primary key,
  step    text not null,
  status  text not null,
  detail  text,
  count   int,
  ms      int,
  at      timestamptz not null default now()
);

create table if not exists cto_recommendations (
  id          uuid primary key default gen_random_uuid(),
  severity    text not null,
  title       text not null,
  detail      text not null,
  action      text not null,
  metric      text,
  created_at  timestamptz not null default now()
);
`
  return sql
}

// ───────────────────────────── package.json + tsconfig + .env.example ─────────────────────────────
export function packageJson(): string {
  return JSON.stringify(
    {
      name: 'overmind-generated-backend',
      private: true,
      type: 'module',
      version: '0.1.0',
      description: 'Aiven-native backend generated by Overmind Surgeon (replaces Supabase).',
      scripts: {
        start: 'NODE_ENV=production tsx server/index.ts',
        dev: 'tsx watch server/index.ts',
        'apply-schema': 'tsx server/apply-schema.ts',
        typecheck: 'tsc --noEmit',
      },
      dependencies: {
        '@hono/node-server': '^1.13.7',
        dotenv: '^16.4.7',
        hono: '^4.6.14',
        kafkajs: '^2.2.4',
        pg: '^8.13.1',
      },
      devDependencies: {
        '@types/node': '^22.10.2',
        '@types/pg': '^8.11.10',
        tsx: '^4.19.2',
        typescript: '^5.7.2',
      },
    },
    null,
    2,
  )
}

export function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        lib: ['ES2022'],
        strict: true,
        esModuleInterop: true,
        allowImportingTsExtensions: true,
        noEmit: true,
        types: ['node'],
      },
      include: ['server'],
    },
    null,
    2,
  )
}

export function envExample(): string {
  return `# Aiven-native backend (generated by Overmind Surgeon)
DATABASE_URL=            # target Aiven Postgres
PROJECT_CA_CERT=         # base64 CA (injected by Aiven Apps; optional locally)

# Realtime via Aiven Kafka (unset → in-process bus)
KAFKA_BROKERS=
KAFKA_USERNAME=avnadmin
KAFKA_PASSWORD=
KAFKA_SSL_CA_PATH=./ca.pem
KAFKA_TOPIC=overmind.app.outbox

# Own auth
AUTH_SECRET=change-me
AUTH_DEV=true            # return magic codes in the API response (dev only)

# Vector search (optional)
OPENAI_API_KEY=

PORT=8789
`
}
